version: '3.8'
services:
  feed-generator:
    build: .
    ports:
      - '3000:3076'
    env_file:
      - .env
    environment:
      - FEEDGEN_PORT=3000
      - FEEDGEN_HOSTNAME=${FEEDGEN_HOSTNAME}
      - FEEDGEN_LISTENHOST=0.0.0.0
      - FEEDGEN_SQLITE_LOCATION=/app/data/db.sqlite
      - FEEDGEN_SUBSCRIPTION_ENDPOINT=wss://bsky.network
      - FEEDGEN_PUBLISHER_DID=${FEEDGEN_PUBLISHER_DID}
    volumes:
      - ./data:/app/data
